name: dpctl

on:
  workflow_dispatch:
    inputs:
      ref:
        description: git ref
        required: true
        default: gold/2021
      label:
        description: label
        required: true
        default: dppy-ci

env:
  PACKAGE_NAME: dpctl
  MODULE_NAME: dpctl

jobs:
  build_linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout dpctl
        uses: actions/checkout@v3
        with:
          repository: IntelPython/dpctl
          path: dpctl
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Setup conda-build
        uses: ./.github/actions/conda-build

      - name: Build conda package
        working-directory: dpctl
        env:
          CHANNELS: -c defaults -c intel --override-channels
        run: ../scripts/build_conda_package.sh ${{ matrix.python }}

      - name: Move conda package to current folder
        run: mv $CONDA/conda-bld/linux-64/${{ env.PACKAGE_NAME }}-*.tar.bz2 .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }} ${{ runner.os }} Python ${{ matrix.python }}
          path: ${{ env.PACKAGE_NAME }}-*.tar.bz2

      - name: Setup anaconda-client
        uses: ./.github/actions/anaconda-client

      - name: Upload to anaconda channel
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          LABEL: ${{ github.event.inputs.label }}
        run: anaconda --token $ANACONDA_TOKEN upload --user dppy --label $LABEL ${PACKAGE_NAME}-*.tar.bz2

