name: dpctl

on: push

env:
  PACKAGE_NAME: dpctl
  MODULE_NAME: dpctl

jobs:
  build_linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout dpctl
        uses: actions/checkout@v3
        with:
          repository: IntelPython/dpctl
          path: dpctl

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Install conda-build
        run: conda install conda-build
      - name: Build conda package
        run: |
          CHANNELS="-c defaults -c intel --override-channels"
          VERSIONS="--python ${{ matrix.python }}"
          TEST="--no-test"
          conda build \
            $TEST \
            $VERSIONS \
            $CHANNELS \
            conda-recipe
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }} ${{ runner.os }} Python ${{ matrix.python }}
          path: /usr/share/miniconda/conda-bld/linux-64/${{ env.PACKAGE_NAME }}-*.tar.bz2

