name: dpnp

on:
  workflow_dispatch:
    inputs:
      ref:
        description: git ref
        required: true
        default: gold/2021
      label:
        description: label
        required: true
        default: dppy-ci

env:
  PACKAGE_NAME: dpnp
  MODULE_NAME: dpnp

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout DPNP
        uses: actions/checkout@v3
        with:
          repository: IntelPython/dpnp
          path: dpnp
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Checkout oneDPL
        uses: actions/checkout@v3
        with:
          repository: oneapi-src/oneDPL
          path: oneDPL
          ref: oneDPL-2021.6.1-release

      - name: Setup conda-build
        uses: ./.github/actions/conda-build

      - name: Set DPLROOT
        run: echo "DPLROOT=$GITHUB_WORKSPACE/oneDPL" >> $GITHUB_ENV

      - name: Build conda package
        working-directory: dpnp
        env:
          CHANNELS: -c dppy/label/dev -c intel -c defaults --override-channels
        run: ../scripts/build_conda_package.sh ${{ matrix.python }}

      - name: Move conda package to current folder
        run: mv $CONDA/conda-bld/linux-64/${{ env.PACKAGE_NAME }}-*.tar.bz2 .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }} ${{ runner.os }} ${{ matrix.python }}
          path: ${{ env.PACKAGE_NAME }}-*.tar.bz2

      - name: Setup anaconda-client
        uses: ./.github/actions/anaconda-client

      - name: Upload to anaconda channel
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          LABEL: ${{ github.event.inputs.label }}
        run: anaconda --token $ANACONDA_TOKEN upload --user dppy --label $LABEL ${PACKAGE_NAME}-*.tar.bz2
