name: dpnp

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python: ["3.8", "3.9"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: IntelPython/dpnp
          ref: master
          fetch-depth: 0

      - name: Checkout oneDPL
        uses: actions/checkout@v3
        with:
          repository: oneapi-src/oneDPL
          path: oneDPL
          ref: oneDPL-2021.6.1-release

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Install conda-build
        run: conda install conda-build

      - name: Build conda package
        run: ./scripts/build_conda_package.sh ${{ matrix.python }} $GITHUB_WORKSPACE/oneDPL

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dpnp ${{ runner.os }} ${{ matrix.python }}
          path: /usr/share/miniconda/conda-bld/linux-64/dpnp-*.tar.bz2
