name: numba-dppy / Windows

on:
  workflow_dispatch:
    inputs:
      ref:
        description: git ref
        required: true
        default: gold/2021
      label:
        description: label
        required: true
        default: dppy-ci

env:
  PACKAGE_NAME: numba-dppy

jobs:
  main:
    runs-on: windows-latest

    strategy:
      matrix:
        python: ["3.8", "3.9"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout DPNP
        uses: actions/checkout@v3
        with:
          repository: IntelPython/numba-dppy
          path: numba-dppy
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Setup conda-build
        uses: ./.github/actions/conda-build-windows

      - name: Build conda package
        working-directory: numba-dppy
        env:
          CHANNELS: -c dppy/label/dppy-ci -c dppy/label/dev -c intel -c defaults --override-channels
        run: conda build --no-test --python ${{ matrix.python }} ${{ env.CHANNELS }} conda-recipe

      - name: Move conda package to current folder
        run: move $env:CONDA\conda-bld\win-64\${{ env.PACKAGE_NAME }}-*.tar.bz2 .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }} ${{ runner.os }} ${{ matrix.python }}
          path: ${{ env.PACKAGE_NAME }}-*.tar.bz2

      - name: Setup anaconda-client
        uses: ./.github/actions/anaconda-client-windows

      - name: Upload to anaconda channel
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          LABEL: ${{ github.event.inputs.label }}
        run: anaconda --token $env:ANACONDA_TOKEN upload --user dppy --label $env:LABEL ${{ env.PACKAGE_NAME }}-*.tar.bz2
